var images=[["images/one.jpg"," One Piece - It is really difficult to sum up the story of a series with hundreds and hundreds of episodes, but we can guarantee you that the main character, Luffy, will provide you a meaningful life lesson. He will teach you that if you decide to accomplish something, you should give your all and fight to achieve your goal till the last moment of your life. This message alone makes this anime great. "],
["images/nogame.png","No Game No Life - This brilliant anime can be addicting for gamers thanks to its unique plot and concept of a fantasy world where almost everything is governed by specific rules which one must follow at all times. The two protagonists are siblings named Shiro and Sora, who are violently transported to a different world that is run by games, and where they must develop a lifestyle to survive in a world where games are not so cool and innocent. "],
["images/psy.jpg","Psycho-Pass - is a smart series that deeply analyzes free will and whether or not a person’s “hue,” when cloudy, can determine if they will become a threat to society. Using a special weapon known as the Dominator, detectives are able to continuously read and send psychological data to determine a person’s crime coefficient. Depending on how clouded a person’s hue is, they will either receive mandatory rehabilitation or be executed on the spot. Fans of Minority Report should watch this anime."],
["images/akame.jpg"," Akame ga Kill! - According to reviews, it’s quite possible you will find its first couple of episodes boring, but as the story unfolds, it becomes one of the most captivating fighting anime you may ever see. The story focuses on a country boy named Tatsumi who sets out on a journey to the Capital to make a name for himself and meets a seemingly dangerous group of assassins known as Night Raid. Will you join him on his journey?"],
["images/opm.png","One-Punch Man - One-Punch Man follows a hero who can end all his fights with a single punch, and that gets him frustrated. Now you might be thinking, what’s so interesting about that? Don’t you want to see the hero struggling to kill his enemy? Well, not this time. Here you will see a super-overpowered hero struggling to find a stronger enemy, struggling to feel the thrill and adrenaline of the fights he once felt when he was weak. Was his training to become strong not worth it after all? Watch the show to get your answers."],
["images/trigun.jpg","Trigun - According to critics and fans, Trigun combines some of the funniest, most absurd, and at the same time intellectual dialogue with powerful drama and sense of what you could also consider to be horror in emotional terms. Just to get more of an idea, Vash, the protagonist, is one of the most contradictory characters in any anime you will ever see. He’s a gunfighter who hates killing but he does it anyway. He’s almost unbreakable, yet very vulnerable. He has the power to destroy all life, but gets upset at the death of a bug. With a $60 billion double price tag on his head, he’s also the most sought after man on the planet!"],
["images/samurai.jpg","Samurai Champloo - The story of this magnificent anime is about Jin, a traditional and very skilled samurai; Mugen, an innovative and equally skilled samurai; and Fuu, a girl who works at a teahouse. When Jin and Mugen get caught and are about to be executed, Fuu saves their lives and in return makes them promise to help her find the Samurai Who Smells Like Sunflowers. I know you probably think the plot of this anime sounds simple and childish, but trust us when we say it’s worth giving it a try."],
["images/soul.jpg","Soul Eater - What most fans appear to like about Soul Eater is that it has something new to offer in terms of story, setting, the personas of the main characters, and artistic style. The story centers on the Shibusen, a school for “Weapons and Masters” in the fictional town of Death City, Nevada. To get a more distinct understanding, a weapon in Soul Eater is a person born with the ability to transform into a Weapon, not just any weapon but the one they were born as."],
["images/ghoul.jpg","Tpkyo Ghoul - Ghouls are terrifying creatures that feed on human flesh. When Kaneki is almost killed in an attack, he transforms into a half-ghoul, half-human hybrid and is forced to adapt to their lifestyle in order to survive. Is this show good? Yes, without a doubt, but our advice is that if you happen to find gore disturbing, then you should watch the censored version."],
["images/metal.jpg"," Fullmetal Alchemist - Fullmetal Alchemist became one of the most popular anime in both America and Japan because of its extremely touching story. That story revolves around Edward and Alphonse Elric, who will try anything they can to bring their mother back from death by attempting human transmutation. If you think that an anime series can’t make you cry, then try to watch this one without tearing up."],
["images/cod.jpg","Code Geass - Code Geass is set in an alternate universe after Japan’s conquest by the Holy Britannian Empire with their powerful new robot weapons, the Knightmare Frames, stripping Japan and its citizens of all rights and freedoms and renaming the country Area 11.  Lelouch is a Britannian prince who gave up his right to the throne after his mother was murdered and has vowed to destroy his father, the emperor and Britannia. It’s always interesting when family matters mix with a thirst for geopolitical conquest and domination, no?"],
["images/bleach.jpg","Bleach - High school student Kurosaki Ichigo is unlike any other kid because he can see ghosts. After an accident with a hollow in the woods, he received power. So begins Kurosaki Ichigo’s training and duty as a Shinigami, Soul Reaper. If you liked The Sixth Sense, then you will most likely love this series."],
["images/fry.png","Fairy Tail - In a world where magic is commonly used and sold, a team of guild members takes on various missions to earn enough money to pay the rent. Among them are Lucy, a celestial spirit mage, Natsu, a fire dragon slayer, and Happy, a blue-winged cat. Welcome to Fairy Tail—a world where magic can buy everything."],
["images/sao.jpg"," Sword Art Online - In the year 2022, gamers worldwide have lined up on launch day for Sword Art Online, a hotly-anticipated MMORPG that lets players connect to an immersive virtual reality world with special helmets called Nerve Gear. Kirito is one such gamer who is eager to jump back into action, having spent a great deal of time as a beta tester, and quickly becomes friends with newbie warrior Klein. What happens next? You will have to check out the series to see what makes this a top anime!"],
["images/ball.jpg","Dragon Ball Z - After learning that he is from another planet, a warrior named Goku and his friends are prompted to defend it from an onslaught of extraterrestrial enemies. In what might be the most famous Asian anime of all time in the West, Dragon Ball Z was and will always be to many fans one of the most influential cartoons ever created."],
["images/naruto.jpg","Naruto - Naruto Uzumaki is a loud, hyperactive, adolescent ninja who constantly searches for approval and recognition, as well as to become Hokage, who is acknowledged as the leader and strongest of all ninjas in the village. The story is absolutely beautiful and has epic fights combined with deep emotion and unpredictable story changes that will blow your mind."],
["images/titan.jpg","Attack on Titan - The best action anime according to Ranker, Attack on Titan, is truly a ground-breaking anime. After his hometown is destroyed and his mother is killed, young Eren Jaegar vows to cleanse the earth of the giant humanoid Titans that have brought humanity to the brink of extinction. This is a truly fantastic anime on many levels: the story, the imagery, the vision, and the atmosphere. The basic premise of mindless giants that eat people might sound silly and even grotesque on paper, but watching it leaves you with a much different feeling. "],
["images/diary.jpg","Future Diary - One of the most fascinating stories we have ever seen in anime history, the hero of this series is given a diary that can predict the future and is thrown into a battle with eleven others where the last survivor becomes God. Sounds pretty sweet, no? Without a doubt, Future Diary is a gripping series. Needless to say, the story is a mega-bonus for sci-fi/anime fans. "],
["images/death.jpg","Death Note - This very dark series has been voted the best anime of all time in Japan.  One of the things many dedicated fans find interesting about Death Note is that the protagonist isn’t your typical good guy, like your everyday stereotypical hero. The fact that this series goes where few others have dared to go in terms of a moral theme is definitely one of the reasons you’ll find this series so enthralling. "],
["images/erased.jpg","Erased is pure genius. Not only are the graphics and fight scenes incredible, but the way the characters and storyline are written, you’ll find yourself hooked from the first episode. At least I was. Erased is a story in which the main character can go back in time in a process he calls “revival.” When his mother is killed, he goes back to his childhood in order to find the killer and stop a rash of kidnappings that happened at that time."],
["images/hunter.jpg"," Hunter x Hunter - Due to a very recent remake it's almost pointless me discussing the original Hunter x Hunter without starting a war about which one is better, new or old.  The reasons I have gone with the original series are because I prefer the animation style in this one... I can't explain it but the animation on the remake looked too computer generated for my taste, (some nice colours but I found the characters to look featureless and undistinguished). I also believe overall the original has a better soundtrack. That's just my opinion. Either version of Hunter x Hunter is acceptable. Anyway if you enjoy action/adventure, anime, then this one is right up your street. Recommended to fans of shows like Inuyasha, Rurouni Kenshin, and Yu Yu Hakusho."],
["images/dark.jpg"," Darker than Black - How can an anime with so many flaws make this list? There's a few anime on this list that would fall under that question, DTB is certainly one of them. Why you ask? It's one of those anime that just dives right in and is very confusing at the beginning. Not to mention that it takes time to become emotionally invested in the characters. However when DTB gets good, it's very good. A well directed anime with, superpowers, suspense, mystery and an interesting anti-hero character."],
["images/GL.jpg","Guran Lagan - damn near impossible to describe. Off the scale action, sheer absurdity. This is an anime where characters dream and reach to do the impossible, off the chart levels of epicness, realism holds no merit here. This sums it up.... <<I knew a man who once said death smiles at us all, all a man can do is smile back>>.  pats self on back for managing to work in a relevant Gladiator quote that can be applied to this anime XD"],
["images/berserk.jpg","Berserk - This series has perhaps the greatest character development of any anime ever made, you become attached to each character who each has well fleshed out personalities comprised of individual qualities, flaws, and ideals. If you hold merit for engaging plot, are exhilarated by action scenes with large doses of violence and don't abhor nudity this is definitely the anime series for you.  It's one of the best anime I've ever seen, the only thing that holds it back as an anime series is one tedious flaw, you'll have to watch it, to find out for yourself. "],
["images/durara.jpg","Durarara - Look it's Baccano! oh wait, no it's the imitator of Baccano! The similarities between the two are plenty, it shouldn't come as a surprise as both anime were made largely be the same team. They took the elements that made Baccano! a success (mystery killer, large cast of characters, extreme violence) and rehashed them for this. If you love one the odds are you'll also love the other. The only huge difference is length and setting. While it's predecessor was original and had a great ending, the same can't be said for this work. However it is a quality anime, recommended to mystery/action fans."],
["images/mob.png","Mob Psycho 100 - is simply the best action series of the past several years, thanks to the peerless animation of Studio BONES, imaginative characters, and a whole lot of heart. Mob is a middle school kid who happens to have incredible psychic powers, and he inevitably uses them to fight other psychics in outlandish battles. But Mob Psycho 100 deviates from most series of its kind by being a surprisingly deep character study, especially in its second season. "],
["images/evan.jpg","Evangelion - is so monumental, so influential in the history of Japanese culture, that it's worth watching no matter what. Even if you don't like mecha shows about giant fighting robots, which is what Eva is at a high level. Even if you can't stand protagonist Shinji Ikari, a depressed teenager who can't deal with his hormones, his daddy issues and the insane save-the-Earth circumstances he finds himself in. Even if you're disappointed that by the end, Evangelion doesn't really know how to follow through on the mysteries, themes, and characters it's developed along the way. There's just so much in Evangelion: it's dense with biblical imagery and psychoanalysis and what-the-hell moments that have inspired countless games and anime since the '90s. "],
["images/hero.png","My Hero Academia - The best shonen (teen) action series currently going. My Hero Academia is the anime take on the X-Men, except most humans, rather than a rare few, develop Quirks, which are strange powers. The series follows a group of high school kids training to become the next wave of heroes, and thanks to a fun cast and brisk pacing, it's a prime candidate for binging. My Hero Academia is unabashedly earnest, which in the wrong hands could end up trite, but here it just works, and will likely have you pumping your fists when protagonist Midoriya and his classmates fight with all their hearts. Maybe the most surprising thing about My Hero is that it stars an honest-to-god smarter, more nuanced take on Superman than we've ever seen in a movie or TV adaptation of the DC hero. All Might is a treasure."],
["images/neverland.png","The Promised Neverland - It's hard to describe The Promised Neverland without giving away at least one of its many shocking twists, but it's the anime version of a page-turner—every episode ends with the tension dialed to 11, and you simply have to see what happens next. What briefly seems like a heartwarming story about the kids in an idyllic orphanage quickly turns into a psychological thriller, as the three oldest children try to plot an escape. The Promised Neverland loves to show how smart its characters are with I knew that you knew that I knew one-upmanship, but hell, the cliché works when the characters are this much fun to watch together, and the twists come this fast and furious. Watch a couple episodes, and it's hard not to immediately devour the rest of the series."],
["images/haiku.png"," Haikyu - Don't mind don't mind! is what the members of Haikyu's high school volleyball team say to each other whenever they lose a point, and that positivity radiates throughout the entire show, which casts volleyball as the most thrilling sport in history. Haikyu is a conventional sports anime, but tuned to perfection, with a cast of underdogs bonding over their love for the sport as they compete against increasingly skilled rival schools. The show really works because of the dichotomy of pint-sized, endlessly energetic spiker Hinata and arrogant setter Kageyama, who make an unbeatable pair as they learn to work together. We promise you don't have to care about volleyball to love this show. They're just such good boys, and they deserve to win."],
],gallery=[];

for(var i=0;i<1;i++)
    gallery[i] = images[Math.floor(Math.random()*30)];

addEventListener("load",function(){
    var a = document.getElementById("gallery");
    for(var i=0;i<gallery.length;i++){
        var b = document.createElement("div");
        var c = document.createElement("div");
        var d = document.createElement("div");
        b.className = "gallery_item";
        c.className = "gallery_item_image";
        d.className = "gallery_item_title";
        c.appendChild(new Image).src = gallery[i][0];
        d.innerHTML = gallery[i][1];
        a.appendChild(b).appendChild(c).parentElement.appendChild(d);
    }
});